theme: jekyll-theme-tactile
include: [".well-known", ".well-known/brave-rewards-verification.txt"]
title: Конста Суомалайнен / Konsta Suomalainen
description: Особиста сторінка з оповіданнями та фотографіями / Personal page with short stories and photos
